### ISSUE TITLE
Best practice to delete entire rows and columns

### ISSUE THREAD

**Issue by talegari** [HenrikBengtsson/listenv#34]
Dear Henrik,

To delete a row (or a column), I am currently doing this.

```
library("listenv")
x           <- as.listenv(1:6)
dim(x)      <- c(2, 3)
dimnames(x) <- list(c("a", "b"), c("A", "B", "C"))
x           <- x[1:2, c(1,3)]                      # remove second column
x
```

- Is this the optimized way to do it? 
- Does this result in not copying the entire matrix?
- After dropping a row/col, do I need to a call `gc` to return memory?

-- I require to maintain large matrices on a shoe-string budget. New rows and columns keep getting added and deleted. Please suggest an idea, if possible!

Regards,
Srikanth

**Comment by HenrikBengtsson** [comment]
You can also use
```sh
x <- x[, -2]
```
do drop a column.

Unfortunately, all subsetting will create a full new copy, so think about it as if you do:
```sh
y <- x[, -2]
```
and afterward `x` and `y` are different objects.

To clarify how list environments work, I should say the listenv package was born for the purpose of supporting the future package, which needs it in order to iterate of elements in an environments using indices (not just names).  It wasn't designed for the purpose of providing a memory efficient container per se.

Having said this, since `x` is an environment, one can, as for any environment, drop elements no longer of interest without creating copies.  When `x` is a vector (i.e. `dim(x)` is `NULL`), you can assign `NULL` to an individual element in order to delete it, e.g.
```r
> library("listenv")
> x <- as.listenv(1:6)
> x
A 'listenv' vector with 6 unnamed elements.
> x[[2]] <- NULL
> x
A 'listenv' vector with 5 unnamed elements.
> unlist(x)
[1] 1 3 4 5 6
```
This approach will _not_ create a new copy.

However, it does _not_ work to assign `NULL` to remove multiple elements, e.g.
```r
> x <- as.listenv(1:6)
> x[2:3] <- NULL
Error: Replacement has zero length
```
[ ] I cannot see a reason for not supporting the above; it would fit how pure R lists work.  On the other hands, there could be a specific reason for why this is not supported - my memory is bad right now.  I'll add it to the todo list.


Though, if you don't mind `NULL` values, which are the smallest object in R, you can at least assign `NULL` to their values using (this is how lists also work):
```r
x[2:3] <- list(NULL)
> x
A 'listenv' vector with 6 unnamed elements.
> str(as.list(x))
List of 6
 $ : int 1
 $ : NULL
 $ : NULL
 $ : int 4
 $ : int 5
 $ : int 6
```
This also works when you work with dimensions, e.g.
```r
> library("listenv")
> x <- as.listenv(1:6)
> dim(x) <- c(2, 3)
> dimnames(x) <- list(c("a", "b"), c("A", "B", "C"))
> x
A 'listenv' matrix with 6 unnamed elements arranged in 2x3 rows ('a', 'b') and columns ('A', 'B', 'C').
> as.list(x)
  A B C
a 1 3 5
b 2 4 6

> x[,2] <- list(NULL)
> x
A 'listenv' matrix with 6 unnamed elements arranged in 2x3 rows ('a', 'b') and columns ('A', 'B', 'C').
> as.list(x)
  A B    C
a 1 NULL 5
b 2 NULL 6
```
So for your needs, I would do the latter for now if that works for you.

**Comment by HenrikBengtsson** [comment]
The following now work in the [develop](https://github.com/HenrikBengtsson/listenv/tree/develop) version:
```r
library("listenv")
x <- as.listenv(1:6)
dim(x) <- c(2, 3)
dimnames(x) <- list(c("a", "b"), c("A", "B", "C"))
print(x)
## A 'listenv' matrix with 6 elements (unnamed) arranged in 2x3 rows ('a', 'b') and columns ('A', 'B', 'C').

x[, 2] <- NULL ## Drop 2nd column
print(x)
## A 'listenv' matrix with 4 elements (unnamed) arranged in 2x2 rows ('a', 'b') and columns ('A', 'C').
```

**Comment by HenrikBengtsson** [comment]
FYI, the above is supported by listenv 0.7.0, which is now on CRAN.
